# Generated by Django 4.2.7 on 2023-12-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_alter_recipe_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='products',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default=None, upload_to='C:\\Users\\kabaa\\Desktop\\Python\\Last\\areckitchen\\static', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
