# Generated by Django 4.2.7 on 2023-12-24 11:29

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0004_recipe_products_alter_recipe_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(default=None, upload_to=pathlib.PureWindowsPath('C:/Users/kabaa/Desktop/Python/Last/areckitchen/res/static')),
        ),
    ]
